### ISSUE TITLE
Hosting of PrOType container image

### ISSUE THREAD

**Issue by TBradley27** [TalhoukLab/PrOType#61]
Hello,

I am Thomas, a research associate working in James Brenton's lab in Cambridge, UK

Many thanks for building such an awesome tool! I look forward to using it.

As discussed in the latest OCAC-OTTA and MOCOG meetings, one of my research aims is to use combined genomic and transcriptomic data from high-grade serous carcinoma for what would hopefully be useful for both improved HGSC subtype classification and prognostication

With that in mind, I hope to better understand ProType and how exactly it relates to the OTTA and MOCOG data I am currently working with.

I was just wondering whether the current instance of PrOtype is hosted anywhere? As in is it hosted on image hubs such as docker hub or amazon web services? Alternatively, is there a conda recipe for easy installation of the tool?

The reason that I ask this, is that workflow management software such as snakemake and nextflow is becoming more and more popular in bioinformatics. However, for automated use of most tools, they require that the tools are already hosted as an image, or as a conda recipe. Whereas from the reading the current ProType documentation, it seems that the requirements is for users to build the image from scratch. 

Building docker or singularity images from scratch can be difficult for non-root users, and therefore limits the ability to apply this tool in many working environments. However, if users were simply to pull a pre-built image from a remote repository hub, then this was ease access and use of this application

P.S. Even without hosting on a specialised repo hub such as docker hub, even having the image as a file as a release within GitHub itself would be useful

Many thanks in advance,
Thomas

**Comment by dchiu911** [comment]
Hi @TBradley27 we are hosting PrOType as a shiny app on [shinyapps.io](https://www.shinyapps.io/). Please see the current version of the app hosted [here](https://ovcare.shinyapps.io/PrOType/). The **Help** tab in the app should help you get started with what we have implemented.
